name: Mask Environment Variable

on:
  push:
    branches:
      - main
      - github-action-test

jobs:
  mask-env-var:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set and Mask Environment Variable
        run: |
            echo "This is a test" > test.txt
            ACCESS_TOKENS=$(cat test.txt)
            echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
            echo "::add-mask::$ACCESS_TOKEN"

      - name: Use masked environment variable
        run: | 
          echo "${{ env.ACCESS_TOKEN }}"
